{{- range .Values.clusters }}
{{- if .infra.enabled }}
{{- if .infra.externalSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-infra-resources
  source:
    repoURL: https://github.com/sarubhai/argo-cd-app-of-apps.git
    targetRevision: {{ .infra.externalSecrets.version }}
    chart: external-secrets
    path: app-of-apps-configurable/infra-charts/external-secrets
    helm:
      releaseName: external-secrets
      valueFiles:
        - {{ .infra.valueFiles }}
      # version: v3
  destination:
    name: {{ .name }}
    namespace: kube-system
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
{{- end }}
{{- end }}
{{- end }}
