{{- range .Values.clusters }}
{{- if .infra.enabled }}
{{- if .infra.reloader.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "reloader"}}
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-infra-resources
  source:
    repoURL: https://github.com/sarubhai/argo-cd-app-of-apps.git
    targetRevision: {{ .infra.reloader.version }}
    # chart: reloader
    path: app-of-apps-configurable/infra-charts/reloader
    helm:
      releaseName: reloader
      valueFiles:
        - {{ .infra.valueFiles }}
      # version: v3
  destination:
    name: {{ .name }}
    namespace: kube-system
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
{{- end }}
{{- end }}
---
{{- end }}
