apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Kubernetes resources to be managed by kustomize
resources:
  - app-of-apps.yaml
  - apps/
# Customizations that need to be made
# commonLabels:
#   templating: kustomize

# Common Transformers
# namePrefix: k8s-
# nameSuffix: -demo
# namespace: demo
# commonLabels:
#   team: Tech
# commonAnnotations:
#   branch: main
# images:
#   name: nginx
#   newName: httpd
#   newTag: 2.4

# patches:
#   - target:
#       kind: Deployment
#       name: app-deployment
#     patch: |-
#       - op: replace
#       path: /spec/replicas
#       value: 3