apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - matrix:
      generators:
      ## - clusters: {} # Automatically use all clusters defined within ArgoCD [ .name .server ]
      - list:
          elements:
          - cluster: dev
            url: https://kubernetes.default.svc
          - cluster: stg
            url: https://kubernetes.default.svc
          - cluster: prod
            url: https://kubernetes.default.svc
      - git:
          repoURL: https://github.com/sarubhai/argo-cd-app-of-apps.git
          revision: HEAD
          directories:
          - path: appset/infra-charts/*
  template:
    metadata:
      name: '{{path.basename}}-{{cluster}}'
    spec:
      project: k8s-infra-resources
      source:
        repoURL: https://github.com/sarubhai/argo-cd-app-of-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc ## {{server}}
        # name: {{name}}
        namespace: '{{cluster}}' # '{{path.basename}}-{{cluster}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
