apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-cd
spec:
  project: k8s-cluster-tools
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.6
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    # name: in-cluster
    namespace: dev-external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
