apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.5
    helm:
      valueFiles:
        - ../../helm-values/external-secrets/{{env}}.values.yaml
  destination:
    namespace: external-secrets
    server: {{k8s_api_server}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
