apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Kubernetes resources to be managed by kustomize
resources:
  - external-secrets.yaml
  - reloader.yaml
  - sealed-secrets.yaml
# Customizations that need to be made
# commonLabels:
#   template: kustomize