apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 1.1.0
    helm:
      valueFiles:
        - ../../helm-values/sealed-secrets/{{env}}.values.yaml
  destination:
    namespace: sealed-secrets
    server: {{k8s_api_server}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
