apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        namespace: mydev
      - cluster: stg
        url: https://kubernetes.default.svc
        namespace: mystg
      - cluster: prod
        url: https://kubernetes.default.svc
        namespace: myprod
  - git:
      repoURL: https://github.com/sarubhai/argo-cd-app-of-apps.git
      revision: HEAD
      directories:
      - path: 2_appset/infra-charts/*
  template:
    metadata:
      name: '{{path.basename}}-{{cluster}}'
    spec:
      project: k8s-infra-resources
      source:
        repoURL: https://github.com/sarubhai/argo-cd-app-of-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        # name: {{cluster}}
        namespace: '{{path.basename}}-{{cluster}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
